name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -r requirements.txt
  
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Debug
      run: echo "github.ref is ${{ github.ref }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
    - name: deploy
      run: |
        echo "Deploying"
        streamlit run Home.py
